### ISSUE TITLE
Builds fail on building .deb using packaged fpm on Travis (since 16.2.1)

### ISSUE THREAD

**Issue by sidneys** [electron-userland/electron-builder#1402]
### Version
16.2.1

### Target
Linux

### Issue
When build DEB packages, Travis always fails (since version 16.2.1).
This issue was occurring sporadically, however since 16.2.1 no builds can be completed at all. 
I also noticed that `electron-builder` uses a packaged legacy `fpm`(1.6.3) instead of using the latest fpm (1.8.1) which is available on Travis. The log hints at  regarding icon png files, however, all image assets are correct (previous solutions for a [similar issue](https://github.com/electron-userland/electron-builder/issues/345) were applied and worked).

Thanks to @develar for a great project.

### Log
`Error: Exit code: 1. Command failed: /home/travis/.cache/electron-builder/fpm/fpm-1.6.3-2.3.1/fpm -s dir -t deb --architecture amd64 --name pb-for-desktop --force --after-install /tmp/electron-builder-qRFsW9/0-2-after-install --after-remove /tmp/electron-builder-qRFsW9/0-3-after-remove --description 
 PushBullet desktop application for macOS, Windows and Linux --maintainer sidneys <sidneys.github.io@outlook.com> --vendor sidneys <sidneys.github.io@outlook.com> --version 4.3.4 --package /home/travis/build/sidneys/pb-for-desktop/build/output/pb-for-desktop_4.3.4_amd64.deb --url https://sidneys.github.io/pb-for-desktop --deb-compression xz --depends gconf2 --depends gconf-service --depends libnotify4 --depends libappindicator1 --depends libxtst6 --depends libnss3 --license MIT --iteration 335 /home/travis/build/sidneys/pb-for-desktop/build/output/linux-unpacked/=/opt/PB for Desktop /home/travis/build/sidneys/pb-for-desktop/icons/linux/1024x1024.png=/usr/share/icons/hicolor/1024x1024/apps/pb-for-desktop.png /home/travis/build/sidneys/pb-for-desktop/icons/linux/128x128.png=/usr/share/icons/hicolor/128x128/apps/pb-for-desktop.png /home/travis/build/sidneys/pb-for-desktop/icons/linux/16x16.png=/usr/share/icons/hicolor/16x16/apps/pb-for-desktop.png /home/travis/build/sidneys/pb-for-desktop/icons/linux/24x24.png=/usr/share/icons/hicolor/24x24/apps/pb-for-desktop.png /home/travis/build/sidneys/pb-for-desktop/icons/linux/256x256.png=/usr/share/icons/hicolor/256x256/apps/pb-for-desktop.png /home/travis/build/sidneys/pb-for-desktop/icons/linux/32x32.png=/usr/share/icons/hicolor/32x32/apps/pb-for-desktop.png /home/travis/build/sidneys/pb-for-desktop/icons/linux/48x48.png=/usr/share/icons/hicolor/48x48/apps/pb-for-desktop.png /home/travis/build/sidneys/pb-for-desktop/icons/linux/512x512.png=/usr/share/icons/hicolor/512x512/apps/pb-for-desktop.png /home/travis/build/sidneys/pb-for-desktop/icons/linux/64x64.png=/usr/share/icons/hicolor/64x64/apps/pb-for-desktop.png /home/travis/build/sidneys/pb-for-desktop/icons/linux/96x96.png=/usr/share/icons/hicolor/96x96/apps/pb-for-desktop.png /tmp/electron-builder-qRFsW9/0-8-PB for Desktop.desktop=/usr/share/applications/pb-for-desktop.desktop
{:timestamp=>"2017-03-23T21:25:38.776398+0000", :message=>"Debian packaging tools generally labels all files in /etc as config files, as mandated by policy, so fpm defaults to this behavior for deb packages. You can disable this default behavior with --deb-no-default-config-files flag", :level=>:warn}
{:timestamp=>"2017-03-23T21:25:39.527322+0000", :message=>"Debian packaging tools generally labels all files in /etc as config files, as mandated by policy, so fpm defaults to this behavior for deb packages. You can disable this default behavior with --deb-no-default-config-files flag", :level=>:warn}
{:timestamp=>"2017-03-23T21:28:44.999718+0000", :message=>"Process failed: tar failed (exit code 1). Full command was:[\"tar\", \"-C\", \"/tmp/package-dir-staging-7519482120988abc1e24f6e1ac72c62beb4378994b7db322f28e83da8241\", \"-J\", \"--numeric-owner\", \"--owner\", \"0\", \"--numeric-owner\", \"--group\", \"0\", \"-cf\", \"/tmp/package-deb-build-2541ce20ef41f45d118691fc87b99dbcc64b8f9641accc75c6dfb11ad6e5/data.tar.xz\", \".\"]", :level=>:error}
    at /home/travis/build/sidneys/pb-for-desktop/node_modules/electron-builder-util/src/util.ts:75:16
    at ChildProcess.exithandler (child_process.js:212:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
From previous event:
    at exec (/home/travis/build/sidneys/pb-for-desktop/node_modules/electron-builder-util/src/util.ts:53:3)
    at /home/travis/build/sidneys/pb-for-desktop/node_modules/electron-builder/src/targets/fpm.ts:175:11
    at Generator.next (<anonymous>)
From previous event:
    at FpmTarget.build (/home/travis/build/sidneys/pb-for-desktop/node_modules/electron-builder/out/targets/fpm.js:226:11)
    at default.each.it (/home/travis/build/sidneys/pb-for-desktop/node_modules/electron-builder/src/platformPackager.ts:109:87)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
From previous event:
    at postAsyncTasks.push.default.map.then (/home/travis/build/sidneys/pb-for-desktop/node_modules/electron-builder/src/platformPackager.ts:109:35)
From previous event:
    at LinuxPackager.packageInDistributableFormat (/home/travis/build/sidneys/pb-for-desktop/node_modules/electron-builder/src/platformPackager.ts:109:8)
    at /home/travis/build/sidneys/pb-for-desktop/node_modules/electron-builder/src/platformPackager.ts:104:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
From previous event:
    at LinuxPackager.pack (/home/travis/build/sidneys/pb-for-desktop/node_modules/electron-builder/out/platformPackager.js:171:11)
    at /home/travis/build/sidneys/pb-for-desktop/node_modules/electron-builder/src/packager.ts:257:24
    at Generator.next (<anonymous>)
    at xfs.mkdir.er (/home/travis/build/sidneys/pb-for-desktop/node_modules/fs-extra/lib/mkdirs/mkdirs.js:37:14)
    at FSReqWrap.oncomplete (fs.js:114:15)
From previous event:
    at Packager.doBuild (/home/travis/build/sidneys/pb-for-desktop/node_modules/electron-builder/out/packager.js:379:11)
    at /home/travis/build/sidneys/pb-for-desktop/node_modules/electron-builder/src/packager.ts:170:52
    at Generator.next (<anonymous>)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
From previous event:
    at Packager.build (/home/travis/build/sidneys/pb-for-desktop/node_modules/electron-builder/out/packager.js:274:11)
    at /home/travis/build/sidneys/pb-for-desktop/node_modules/electron-builder/src/builder.ts:198:33
    at Generator.next (<anonymous>)
From previous event:
    at build (/home/travis/build/sidneys/pb-for-desktop/node_modules/electron-builder/out/builder.js:70:21)
    at Object.<anonymous> (/home/travis/build/sidneys/pb-for-desktop/node_modules/electron-builder/out/cli/build-cli.js:71:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:148:9)
    at bootstrap_node.js:542:3
child_process.js:524
    throw err;`

## Related
- "Error when building Linux build" #1009
- "Deb Fails" #537
- ".deb fails with missing icon_16x16x32.png from fpm" #345

**Comment by develar** [comment]
Please attach the whole log (tar cannot handle situation when files are accessed in parallel).

**Comment by sidneys** [comment]
@develar 
Thanks for the hint. Here is the log: [http://pastebin.com/xhinjnTb](http://pastebin.com/xhinjnTb)

I will try building without tar in the meanwhile.

**Comment by develar** [comment]
Maybe it is fixed in the 16.3.1

**Comment by develar** [comment]
You do `--linux --ia32 --x64 --armv7l` and targets for linux is `AppImage, deb`, right?

**Comment by sidneys** [comment]
@develar 

This is my configuration:

#### package.json
```json
"linux": {
  "icon": "./icons/linux",
  "publish": null,
  "target": [
    "AppImage",
    "deb",
    "pacman",
    "rpm"
  ]
},
```

#### build.js
```bash
build --linux --ia32 --x64 --armv7l
````

Removing `pacman`(and thus, `bsdtar` requirement) didn't help by the way

**Comment by sidneys** [comment]
@develar 
I'm afraid that 16.3.1 didn't fix this issue. Maybe a race condition?

**Comment by sidneys** [comment]
@develar 
I just tested something - removal of `arm` from arches results in an instant build success.
The underlying reason still unclear, however.

**Comment by develar** [comment]
Moved to backlog to keep issue list clear.
