### ISSUE TITLE
nsis-web and nsis, public GitHub: Electron-updater don't start downloading after update-available

### ISSUE THREAD

**Issue by marceloavf** [electron-userland/electron-builder#2377]
After `autoUpdater.checkForUpdates()`, it emmits `update-available` but don't start downloading.
I'm using `GitHub` to publish.

---

* **Electron-updater - Version**: 2.17.3
* **Electron-builder - Version**: 19.48.3
* **Target**:  Windows | nsis-web

**Comment by woo-long** [comment]
me too

**Comment by develar** [comment]
Do you use private GitHub?

**Comment by marceloavf** [comment]
No, it's public GitHub

**Comment by develar** [comment]
2.17.4 works for me, please verify.

**Comment by marceloavf** [comment]
Still not working with 2.17.4

![image](https://user-images.githubusercontent.com/5435657/33879688-5902d9aa-df16-11e7-8b5f-a1d6c10417a7.png)

**Comment by develar** [comment]
Is your old version of app (update from) uses electron-updater 2.17.4?

**Comment by marceloavf** [comment]
Yes, I generate two version with `2.17.4` with some small changes, try to update from my app v1.17.2 that uses the `2.17.4` to 1.17.3 that also use it

**Comment by aenario** [comment]
Hello @develar I just debugged a similar issue and it seem to be related to redirection.

May be it's only for big bundles, but github is redirecting to amazonS3, which is not followed by electron's net package because of the the redirect: "manual". 

I am not sure why you need to manually deal with redirection in this package, and I am confused by the structure between Provider <-> Executor <-> Updater and so on, so I won't be pushing a PR. However, I got it fixed with this hacky monkey patch :

```
const _mp = autoUpdater.httpExecutor.doRequest
    autoUpdater.httpExecutor.doRequest = function (options, callback) {
        const req = _mp.call(this, options, callback)
        req.on('redirect', () => req.followRedirect())
        return req
    }
```

Hope that helps to pinpoint the issue and solve it more definitively.

**Comment by woo-long** [comment]
After upgrading to 2.17.4, download-progress can be called under Mac OS, but it can't be called under Windows

**Comment by develar** [comment]
@aenario If you use private GitHub provider, it is fixed in the electron-updater 2.17.5

**Comment by develar** [comment]
Please in any comment about electron-updater issue provide: 1. provider (GitHub or s3 or ...) 2. target (nsis-web or nsis or appimage)

**Comment by develar** [comment]
electron-updater 2.17.6 released.

If error still here, please enable debug logging to file and provide logs.

```js
const log = require("electron-log")
log.transports.file.level = "debug"
autoUpdater.logger = log
```

**Comment by marceloavf** [comment]
2.17.6 not working here, log:
Wait for 10 minutes and check network resources but no download started.

```
[2017-12-13 08:07:20.136] [info] Checking for update...
[2017-12-13 08:07:26.378] [info] Found version 1.17.8 (url: inovafarma-notificacoes-1.17.8-win.exe)
[2017-12-13 08:07:26.378] [info] Update available.
[2017-12-13 08:07:26.378] [info] { version: '1.17.8',
  files: 
   [ { url: 'inovafarma-notificacoes-1.17.8-win.exe',
       sha512: 'DkjNsoibQyGv+kgFEHxNqDBp2AhYP8+Eo0U94ULfBWpJrQG6Tmvtt0Rc1rmbgeiL2yqUTR39jxsaswo8S7J4Iw==' } ],
  path: 'inovafarma-notificacoes-1.17.8-win.exe',
  sha512: 'DkjNsoibQyGv+kgFEHxNqDBp2AhYP8+Eo0U94ULfBWpJrQG6Tmvtt0Rc1rmbgeiL2yqUTR39jxsaswo8S7J4Iw==',
  packages: 
   { ia32: 
      { path: 'inovafarma-notificacoes-1.17.8-ia32.nsis.7z',
        size: 36392513,
        blockMapSize: 72504,
        sha512: 'hxcOmeN65Duza8SlOUngCZKwoVqnKJRM7njsIAcqK4TJJsQQdeKzvOO9vM7e1lj1VgJKppjjzAvMCWba/CJ/fA==',
        headerSize: 10006 },
     x64: 
      { path: 'inovafarma-notificacoes-1.17.8-x64.nsis.7z',
        size: 42347040,
        blockMapSize: 82951,
        sha512: 'YQnQ7Y6zRb0I4LCh+i3IEMZzyxt4GLfW/4zyl6vcqGd8vN4yuvip8xpg4b90Tx3GCbqI7aAxwqXnnrpbdpLIFg==',
        headerSize: 10006 } },
  sha2: 'f0add7ee083188167b675ddc520dbe6ffb99526b7b6a06a57deb95962c891726',
  releaseDate: '2017-12-12T15:51:34.558Z',
  releaseName: '1.18.0',
  releaseNotes: '' }
[2017-12-13 08:07:26.380] [info] Downloading update from inovafarma-notificacoes-1.17.8-win.exe
```

**Comment by develar** [comment]
@marceloavf Is debug enabled?

**Comment by marceloavf** [comment]
@develar I used your code above

**Comment by develar** [comment]
#2379 merged into this issue.

**Comment by Zamiell** [comment]
Yup, this is easily reproducable. I have set up a test repository that showcases the issue here:
https://github.com/Zamiell/test

This repo is just the `electron-quick-start` repo with some small changes:
* showing the dev tools on start
* showing the app version below the other versions
* adding the auto update code that is told in the official electron builder documentation

Some notes:
* uses electron 1.8.1
* uses the latest versions of electron-builder and electron-updater
* it happens on BOTH nsis and nsis-web
* build target is windows, testing happens in Windows 7

Nothing updates!!!! So this is severe regression.

**Comment by Zamiell** [comment]
Also, monkey patch from above works for me to fix this problem. I put it right before the line of:

```
autoUpdater.checkForUpdatesAndNotify()
```

Also, as a side note, @develar can you update the documentation? It does not explain the difference between `checkForUpdates` and `checkForUpdatesAndNotify`:

![image](https://user-images.githubusercontent.com/5511220/34072879-2f3ec080-e25d-11e7-8387-fd20bcbfe0db.png)

**Comment by sheldhur** [comment]
- electron 1.6.12
- electron-builder latest
- electron-updater 2.17.0-2.17.6
- provider: github (public)
- target: nsis

The same problem for 2.17.0-2.17.6 versions. But in 2.16.3 all is work :)

**Comment by metal-messiah** [comment]
can confirm same problem with 2.17.6

i switched down to 2.16.3 like @sheldhur suggested, and it does now download the file.
new dependencies are 
electron - 1.7.9
electron-builder - 19.49.0
electron-updater - 2.16.3
provider - github (public)
target - nsis

 when i apply the updates though, (tried both quitAndInstall() -- and just manually closing the app) i get the attached error, even though the file exists in the designated path, and the log appears to show no problems.

![image](https://user-images.githubusercontent.com/24296585/34304698-0d625d92-e6f8-11e7-9a19-2f2aeb3c5a46.png)

**Comment by gordonshieh94** [comment]
I did some sleuthing, and found that in BaseUpdater.js:87 of electron-builder
```const destinationFile = _path.join(tempDir, _path.posix.basename(fileInfo.url.pathname));```
should be:
```const destinationFile = _path.join(tempDir, _path.posix.basename(fileInfo.info.url));```

That will download the installer with the proper filename. I just found the fix, so I can't exactly have a clean slate that is reproducible for testing.

Electron 1.7.9
Electron-builder 19.49.0

**Comment by metal-messiah** [comment]
can confirm that the changes @gordonshieh94 suggested worked.  updated BaseUpdater.js and file is now updating as intended.  thanks!

**Comment by develar** [comment]
@gordonshieh94 It looks strange. But — as we do `basename` in any case, resolved URL is not required in our case and probably it is better to avoid complex code like `url.pathname` (where url it is instance of node URL) and use simple string url as in the update info. I will release new version with this fix. Thanks a lot.

**Comment by develar** [comment]
Please try electron-updater 2.17.7

**Comment by marceloromaomultilaser** [comment]
Still not working for me =(

electron - 1.7.5
electron-builder - 19.19.1
electron-updater - 2.17.7
provider - github (private)
target - nsis

![capturar](https://user-images.githubusercontent.com/26793558/34320251-9c16b90e-e7dc-11e7-8e7d-727273d2f63b.PNG)

**Comment by gordonshieh94** [comment]
The monkey patch posted above is still required. develar's commit does seem to address the ENOENT issue that metal-messiah and I are having though.

**Comment by sheldhur** [comment]
Not working

- electron - 1.6.12
- electron-builder - 19.49.2
- electron-updater - 2.17.7
- provider - github (private)
- target - nsis

**Comment by FantasticFiasco** [comment]
Any progress on this issue?

**Comment by sheldhur** [comment]
2.18.2 work for me

- electron - 1.7.10
- electron-builder - 19.51.0
- electron-updater - 2.18.2
- provider - github (public)
- target - nsis

**Comment by FantasticFiasco** [comment]
Works for me to

**Comment by develar** [comment]
Thanks for confirmation.

**Comment by damianobarbati** [comment]
@marceloavf did you solve this? I see a partial download (about 5mb) and my app just quits without emitting `upload-downloaded` event. 

I'm having no help here: https://github.com/electron-userland/electron-builder/issues/2977 :\

**Comment by marceloavf** [comment]
@damianobarbati It's working since 2.18.2 here, one project in GitHub and another in Digital Ocean Spaces, also tested here on Windows 10, I'll take a look and give you any feedback if I find something.

**Comment by damianobarbati** [comment]
Thanks @marceloavf, I'm on:
```
"electron": "^2.0.1",
"electron-builder": "^20.13.4",
"electron-updater": "^2.21.10",
```

Should I downgrade?

**Comment by marceloavf** [comment]
My latest project is working on this versions @damianobarbati, using Digital Ocean Spaces:

```
electron@^1.8.4:
  version "1.8.4"

electron-builder@^20.8.1:
  version "20.8.1"

electron-updater@^2.21.4:
  version "2.21.4"
```

Try them to see if something changes.

**Comment by damianobarbati** [comment]
@marceloavf what do you mean with "_Try them to see if something changes, you can also try to delay your autoUpdate functions too._"?

**Comment by marceloavf** [comment]
You can use `SetTimeout` or `setImmediate` to delay your update function, waiting for your electron app fully loads before trying to check for update.
