### ISSUE TITLE
Different productName (Menu) and file.app Name

### ISSUE THREAD

**Issue by sqwk** [electron-userland/electron-builder#2937]
Is there a way to have a different `productName` (The name that is automatically used in the app's menubar) and the resulting filename.app short of renaming the resulting file manually?

For example Adobe Photoshop is named "Adobe Photoshop CC 2018", but the menu bar inside the app only says "Photoshop".

Currently using:

        "electron": "2.0.0",
        "electron-builder": "20.13.4",

**Comment by develar** [comment]
Please attach here Info.plist of Adobe Photoshop CC 2018 app (open app bundle using Show Package Contents).

**Comment by sqwk** [comment]
Another example would be Visual Studio Code. The executable is called "Visual Studio Code" and the menu says "Code".

I attached two screenshots as .plist files cant be attached/uploaded.

<img width="655" alt="code" src="https://user-images.githubusercontent.com/1353312/40411082-b36b7bd0-5e6f-11e8-9074-eac92161c4de.png">
<img width="645" alt="photoshop" src="https://user-images.githubusercontent.com/1353312/40411094-ba3cda1c-5e6f-11e8-8ef5-0267fc171872.png">

**Comment by mischnic** [comment]
VS Code Info.plist:
```plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>BuildMachineOSBuild</key>
    <string>16G1036</string>
    <key>CFBundleDisplayName</key>
    <string>Code</string>
    <key>CFBundleExecutable</key>
    <string>Electron</string>
    <key>CFBundleIconFile</key>
    <string>Code.icns</string>
    <key>CFBundleIdentifier</key>
    <string>com.microsoft.VSCode</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundleName</key>
    <string>Code</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleShortVersionString</key>
    <string>1.23.1</string>
    <key>CFBundleVersion</key>
    <string>1.23.1</string>
    <key>DTSDKBuild</key>
    <string>14D125</string>
    <key>DTSDKName</key>
    <string>macosx10.1010.10</string>
    <key>DTXcode</key>
    <string>0833</string>
    <key>DTXcodeBuild</key>
    <string>8E3004b</string>
    <key>LSApplicationCategoryType</key>
    <string>public.app-category.developer-tools</string>
    <key>LSMinimumSystemVersion</key>
    <string>10.9.0</string>
    <key>NSHighResolutionCapable</key>
    <true/>
    <key>NSMainNibFile</key>
    <string>MainMenu</string>
    <key>NSPrincipalClass</key>
    <string>AtomApplication</string>
    <key>NSSupportsAutomaticGraphicsSwitching</key>
    <true/>
    <key>NSHumanReadableCopyright</key>
    <string>Copyright (C) 2018 Microsoft. All rights reserved</string>
    <key>CFBundleHelpBookFolder</key>
    <string>VS Code HelpBook</string>
    <key>CFBundleHelpBookName</key>
    <string>VS Code HelpBook</string>
    ...
  </dict>
</plist>
```

**Comment by develar** [comment]
@sqwk It is already fixed in 20.14.7 Please try.

**Comment by sqwk** [comment]
It now overwrites the plist file, but has no effect on the menu bar app name.

**Comment by KrishVikram** [comment]
Hi, any updates on this?

**Comment by pronebird** [comment]
You can extend the `Info.plist` with anything you want:

```
mac:
  target: pkg
  category: public.app-category.tools
  extendInfo:
    LSUIElement: true
    WHATEVER: "YOU LIKE"
```

**Comment by sirtimid** [comment]
This is still not fixed. Applying the following it doesn't change the menu bar app name
```
{
 "mac": {
  "extendInfo": {"CFBundleDisplayName": "Short"}
 }
}
```
