### ISSUE TITLE
"Application icon is not set"on Ubuntu

### ISSUE THREAD

**Issue by perborgen** [electron-userland/electron-builder#3495]
* **Version**: 20.36.2

* **Target**: deb

I'm receiving the following message when I build my app on Ubuntu 18.04:

_default Electron icon is used reason=application icon is not set_

As far as I can tell, I'm setting the icons according to [the docs:](https://www.electron.build/icons) placing them in the /build folder and not specifying anything under "linux" in the "build" config. The full source code can be viewed here:
https://github.com/scrimba/gitspeak-desktop/tree/linux

Here's my build config in package.json:
```
"build": {
    "appId": "com.gitspeak.app",
    "asar": false,
    "publish": {
      "provider": "github",
      "repo": "gitspeak-desktop",
      "owner": "scrimba"
    },
    "mac": {
      "target": [
        "dmg",
        "zip"
      ],
      "icon": "./build/icon.icns",
      "category": "your.app.category.type"
    },
    "win": {
      "target": "NSIS",
      "icon": "./build/icon.icns"
    },
    "linux": {
      "target": "deb",
      "category": "Development"
    }  
  }
```

I've been trying a ton of variations of how to set icon on Ubuntu, but I just can't figure it out, so I'm suspecting that there's some kind of bug here.

Thanks!

**Comment by Tazeg** [comment]
Downgraded to 20.28.4 and it works

**Comment by perborgen** [comment]
That worked! Thank you so much @Tazeg !

**Comment by Tazeg** [comment]
But it still need to fixed in the latest releases.

**Comment by zhaoterryy** [comment]
If you want to use latest electron-builder - although the warning comes up, your icon is still used.

**Comment by Sergey-Churilin** [comment]
@zhaoterryy, @develar 
This issue is reproducible in version 20.39.0 and 20.42.2

**Comment by xland** [comment]
This issue is still there in version 21.2.0
And I can not rollback the electron-builder version
Because lower version of electron-builder will not work with electron 6.0.x

@develar @zhaoterryy

**Comment by defusioner** [comment]
Wasn't this fixed in 22.x releases?
