### ISSUE TITLE
quitAndInstall() Not Restarting App on macOS Big Sur

### ISSUE THREAD

**Issue by robertjkeck2** [electron-userland/electron-builder#5335]
* **Version**: 22.8.1 (electron-builder), 4.3.5 (electron-updater)

* **Electron Version**: 7.3.2
* **Electron Type (current, beta, nightly)**: current

* **Target**: macOS

The auto-update flow (`checkForUpdates`, `update-downloaded`, etc.) is working for Mojave, Catalina, and Big Sur. The update is successfully installed on each version on re-opening of the app. On calling `quitAndInstall` however, the app only relaunches on Mojave and Catalina but fails to restart the app on Big Sur. 

In addition to the traditional `quitAndInstall` call, we've attempted to work around the inability to restart the app on Big Sur using the following relaunch code but these have all failed to successfully relaunch post-update:

```
app.relaunch();
```

```
app.relaunch({ execSync: '/Applications/AppName.app'});
```

```
app.relaunch({ args: process.argv.slice(1).concat(['--relaunch']) });
```

As Big Sur is planned to be release out of beta in the near future, it is probably good to get in front of it to ensure app relaunch in `quitAndInstall` works when users update.

**Comment by johnnyopao** [comment]
Also seeing the same issue. Nothing we've tried so far has relaunched the app

electron-builder `21.1.5`
electron-updater `4.3.4`

**Comment by christxph** [comment]
We are experiencing the same issue on Electron `10.1.3` and electron-builder `22.8.0` but it looks like this was fixed in Electron v11: https://github.com/electron/electron/pull/25864

A backport to prior electron versions is not going to happen according to https://github.com/electron/electron/issues/25626#issuecomment-729493320

**Comment by alectrocute** [comment]
Bumped Electron to `^11.0.0` for our app in production, can confirm that after on Big Sur `11.0.1`, the problem is solved.

**Comment by tom-james-watson** [comment]
Warning - if you use asar, then electron 11 doesn't currently work with electron-builder - https://github.com/electron-userland/electron-builder/issues/5360

**Comment by koenoe** [comment]
Unfortunately we still have this issue with Electron 11 on Big Sur. It works fine on Mojave and Catalina.

**Comment by tom-james-watson** [comment]
With the latest version fo electron (11.1.0), the above bug mentioned (https://github.com/electron-userland/electron-builder/issues/5360) is fixed and `quitAndInstall` is now working as expected on Big Sur for us.

**Comment by johnnyopao** [comment]
this is working for us now after we've upgraded to electron 11

electron: `^11.0.3`
electron-builder: `^22.9.1`
electron-updater: `^4.3.5`

**Comment by alectrocute** [comment]
Still relevant.

**Comment by shadow-light** [comment]
My app was not restarting after closing/updating on Mac. Then I added it to the dock and upon the next update it did restart. Not sure if that's just a coincidence, but perhaps someone else can confirm.

**Comment by douglassllc** [comment]
OS:  Monterey `12.0.1`
Chip:  Apple M1 Max
electron-builder  `22.14.13`
electron-updater `4.6.5` and `5.2.1`

Experiencing the same issue.  Update is downloaded and application quits, but it does not automatically restart.  When I manually start the application after the update it does have the correct version.
